name: Sync GitHub Releases to JSON

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - uses: actions/setup-node@v4

      - name: Update releases.json
        id: update-json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          MANUAL_RUN: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          node <<'EOF'
          const { execSync } = require('child_process');
          const fs = require('fs');

          const isManual = process.env.MANUAL_RUN === 'true';
          const repo = process.env.GH_REPO;
          const file = 'releases.json';

          function gh(path, args = '') {
            return JSON.parse(execSync(`gh api ${path} ${args}`, { encoding: 'utf8' }));
          }

          function getAllReleases() {
            const perPage = 100;
            let page = 1, releases = [], fetched;
            do {
              fetched = gh(`/repos/${repo}/releases?per_page=${perPage}&page=${page}`);
              releases.push(...fetched.filter(r => !r.draft && !r.prerelease));
              page++;
            } while (fetched.length === perPage);
            return releases;
          }

          function getLatestRelease() {
            try {
              const r = gh(`/repos/${repo}/releases/latest`);
              return (!r.draft && !r.prerelease) ? [r] : [];
            } catch (e) {
              return [];
            }
          }

          const existing = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : [];
          const existingMap = new Map(existing.map(r => [r.version, r]));
          const releases = isManual ? getAllReleases() : getLatestRelease();

          const map = new Map(existingMap);  // clone
          let added = 0;

          for (const r of releases) {
            const assets = r.assets.map(a => ({
              name: a.name,
              url: a.browser_download_url,
              size: a.size,
              digest: a.digest  // sha256
            }));
            const version = r.tag_name;
            const entry = {
              version,
              url: r.html_url,
              assets
            };

            if (!map.has(version) || JSON.stringify(map.get(version)) !== JSON.stringify(entry)) {
              map.set(version, entry);
              added++;
            }
          }

          let removed = 0;
          if (isManual) {
            const validVersions = new Set(releases.map(r => r.tag_name));
            for (const version of [...map.keys()]) {
              if (!validVersions.has(version)) {
                map.delete(version);
                removed++;
              }
            }
          }

          const out = [...map.values()].sort((a, b) => b.version.localeCompare(a.version, undefined, { numeric: true }));
          fs.writeFileSync(file, JSON.stringify(out, null, 2));

          fs.appendFileSync(process.env.GITHUB_OUTPUT, [
            `added=${added}`,
            `removed=${removed}`,
            `manual=${isManual}`
          ].join('\n') + '\n');
          EOF

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add releases.json

          if ! git diff --cached --quiet; then
            ADDED="${{ steps.update-json.outputs.added }}"
            REMOVED="${{ steps.update-json.outputs.removed }}"
            MANUAL="${{ steps.update-json.outputs.manual }}"

            if git log --format=oneline -- releases.json | grep -q .; then
              if [ "$ADDED" -gt 0 ]; then
                VERSION=$(jq -r '.[0].version' releases.json)
                MSG="Update releases.json for version $VERSION"
              elif [ "$MANUAL" = "true" ] && [ "$REMOVED" -gt 0 ]; then
                MSG="chore: sync releases.json"
              else
                MSG="Update releases.json"
              fi
            else
              MSG="Initial releases.json with full release history"
            fi

            git commit -m "$MSG"
            git push
          fi
